<?php
namespace Sejmometr;

/**
 * Test class for Deputy.
 * Generated by PHPUnit on 2012-02-09 at 21:44:20.
 */
class EntityTest extends \PHPUnit_Framework_TestCase
{
  public function testStaticRequest() {
    $data = Entity::request("poslowie");

    $this->assertNotNull($data, 'Retrieved data is not null');
    $this->assertTrue(is_array($data), 'Retrieved data deserialized as array');
    $this->assertTrue(sizeof($data) > 0, 'Retrieved data array is bigger than 0');

    $data = Entity::request("error");
    $this->assertFalse($data, 'Faulty call to sejmometr returns FALSE value');

    $data = Entity::request("error");
    $this->assertFalse($data, 'Second call to same url returns same results');

    $deputy = Entity::request("posel/193/info");
    $this->assertTrue(is_object($deputy), 'Retrieved deputy object has valid type');

  }

  /**
   *  @expectedException InvalidArgumentException
   */
  public function testStaticRetrieveException() {
    $test = Entity::retrieve('NonExistingClass', array());
  }


  public function testStaticRetrieve() {
    $test = Entity::retrieve('Sejmometr\\Deputy', array(1,2, 10));

    $this->assertTrue(
      is_array($test) && sizeof($test) == 3,
      'Retrieved deputies data is array and valid value'
    );

    $this->assertTrue(
      $test[10] instanceof Deputy,
      'Selected element of array has valid type'
    );
  }
}
